<div class="col-sm-12 footer">
    <br><br>
    <div class="col-sm-3">
        <div class="footerWidget"> 
            <h4 class="footer-title">A PROPOS DE NOUS</h4>
            <br>
            <h1 class="title-first-letter">SASSIRE GROUP SARL</h1>
            <p class="p-txt">
                &nbsp; une entreprise de services des travaux publics. 
            </p>  
        </div>
    </div>
    <div class="col-sm-3">
        <div class="footerWidget">
            <h4 class="footer-title">Nos Services offerts</h4>
            <br>
            <div class="col-sm-12">
                <ul>
                    <li class = "li-item p-txt-list">Application Web</li><hr>
                    <li class = "li-item p-txt-list">Site-Web</li><hr>
                    <li class = "li-item p-txt-list">Application-Mobile</li><hr>
                    <li class = "li-item p-txt-list">Web Services</li><hr>
                    <li class = "li-item p-txt-list">Application de Bureau</li><hr>
                    <li class = "li-item p-txt-list">IT-Consulting</li><hr>
                    <li class = "li-item p-txt-list">Vente des accessoires Informatiques</li><hr>
                </ul>
            </div>                          
        </div>
    </div>
    <div class="col-sm-3">
        <h4 class="footer-title">Contactez-Nous</h4>
        <br>
        <div class="col-sm-12">
            <ul>
                <li class = "li-item">
                    <a href="#" data-placement="top"
                       title="B.P. 2861 Yaound&eacute; Messa-Cameroun">
                        <span class="glyphicon glyphicon-home">&nbsp;B.P.
                            210 Yaoundé 
                        </span>
                    </a>
                </li><hr>
                <li class = "li-item">
                    <a href="provincialcam@yahoo.fr" data-placement="top"
                       title="provincialcam@yahoo.fr">
                        <span class="glyphicon glyphicon-envelope">&nbsp;contact@sassire.com
                        </span>
                    </a>
                </li><hr>
                <li class = "li-item">
                    <a href="#" data-placement="top"
                       title="T&eacute;l&eacute;phone">
                        <span class="glyphicon glyphicon-phone">&nbsp;(00237) 690 660 199
                        </span>
                    </a>
                </li><hr>
                <li class = "li-item">
                    <a href="#" data-placement="top"
                       title="T&eacute;l&eacute;phone mobile ">
                        <span class="glyphicon glyphicon-phone-alt">&nbsp;243 566 159
                        </span>
                    </a>
                </li><hr>
            </ul>
        </div>                
    </div>
    <div class="col-sm-3">
        <h4 class="footer-title">Rejoinez-Nous</h4>
        <br>
        <p class="p-txt">
            Pour plus d'informations, réjoignez nous sur les réseaux sociaux.
        </p>
        <div class="col-sm-12">
            <div class="footer-icons">
                <a href="https://facebook.com/"><i><span class="glyphicon"><img  class="social-icon-item" src="<?php echo $this->basePath('img/icons/social-icons/skype.png'); ?>"></span></i></a>
                <a href="#"><i><span class="glyphicon"><img  class="social-icon-item" src="<?php echo $this->basePath('img/icons/social-icons/youtube.png'); ?>"></span></i></a>
                <a href="#"><i><span class="glyphicon"><img  class="social-icon-item" src="<?php echo $this->basePath('img/icons/social-icons/twitter.png'); ?>"></span></i></a>
                <a href="#"><i><span class="glyphicon"><img  class="social-icon-item" src="<?php echo $this->basePath('img/icons/social-icons/facebook.png'); ?>"></span></i></a>
                <a href="#"><i><span class="glyphicon"><img  class="social-icon-item" src="<?php echo $this->basePath('img/icons/social-icons/linkedin.png'); ?>"></span></i></a>
                <a href="#"><i><span class="glyphicon"><img  class="social-icon-item" src="<?php echo $this->basePath('img/icons/social-icons/google.png'); ?>"></span></i></a>
            </div>
        </div>     
        <br>   <br>   <br> 

        <h4 class="footer-title">Modes de Paiement</h4>
        <br>
        <p class="p-txt">
            Effectuez vos paiement par Mobile Money ou Orange Money
        </p>
        <div class="col-sm-12">
            <div>
                <a href="https://facebook.com/"><i><span class="glyphicon"><img  class="social-icon-item-paiement" src="<?php echo $this->basePath('img/footer/mobilemoney.png'); ?>"></span></i></a>
                <a href="#"><i><span class="glyphicon"><img  class="social-icon-item-paiement" src="<?php echo $this->basePath('img/footer/orangemoney.png'); ?>"></span></i></a>
            </div>
        </div>        
    </div>
</div>  
<div  class="container" style="background-color: white">
    <div class="container">
        <div class="col-xs-6 copyright"> Copyright © 2016 Sassire All right reserved.</div>
        <div class="col-xs-1"></div>
        <div class="col-xs-5">
            <ul class="list-unstyled list-inline">
                <li><a class="footer-menu-element" href="#">Services</a><span>&nbsp;|&nbsp;</span></li>
                <li><a class="footer-menu-element"  href="#">Réalisations</a><span>&nbsp;|&nbsp;</span></li>
                <li><a class="footer-menu-element" ref="#">Modèles</a><span>&nbsp;|&nbsp;</span></li>
            </ul>
        </div> 
    </div>
</div> 