<!-- Cacher le logo quand le terminal est minuscule -->
<div class="col-lg-12">
    <div class="col-lg-3 bottom hidden-md hidden-sm hidden-xs">
        <div>
            <img class="img-responsive bottom-left" src="<?php echo $this->basePath('img/logos/logo1.png'); ?>" alt="" width="200" height="0" />
        </div>
    </div>
    <div class="col-lg-6 hidden-xs">
        <img class="img-responsive center-block" src="<?php echo $this->basePath('img/logos/logo5.png'); ?>" alt="" width="200" height="0" />
    </div>
    <div class="col-lg-3"></div>
</div>
