<div class="navbar-inverse" style="padding-top:0;padding-bottom:  0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Sassire</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">                 
            <li class="  menu-element"><a href="#">ACCUEIL</a></li>                     
            <li class="  menu-element"><a href="<?= $this->url('application', ['action'=>'service'])  ?>">SERVICES</a></li>
            <li class="  menu-element"><a href="<?= $this->url('application', ['action'=>'realization'])  ?>">REALISATIONS</a></li>
            <li class="  menu-element"><a href="#services">MODELES</a></li> 
            <li class="  menu-element"><a href="#dreamteam<?php //echo $this->url('application/default', array('controller' => 'Index', 'action' => 'team'));  ?>">EQUIPE</a></li>
            <li class="  menu-element"><a href="<?= $this->url('application', ['action'=>'contact'])  ?>">CONTACT</a></li>                        
        </ul>
    </div>
</div>