<link href="https://fonts.googleapis.com/css?family=Cormorant+Upright:700|Dancing+Script:700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Cookie|Cormorant+Upright:400,700|Dancing+Script:700|Great+Vibes|Scheherazade|Tangerine" rel="stylesheet">
<div>
    <div id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
            <li data-target="#myCarousel" data-slide-to="4"></li>
        </ol>

        <!-- Wrapper for Slides -->
        <div class="carousel-inner">
            <div class="item active">
                <!-- Set the first background image using inline CSS below. -->
                <div class="col-xs-12">
                    <div class="col-xs-6">
                        <img class="img-responsive center-block" src="<?php echo $this->basePath('img/slider/slide1.png'); ?>" alt="" />  
                    </div>                    
                    <div class="carousel-caption text-justify" >
                        <div class="col-lg-6"></div>
                        <div class="col-lg-6 pull-right" style="background-color: black; opacity:  0.8;padding-bottom: 15px">
                            <h3 style="color: #EC971F; font-family: 'Cormorant Upright', serif;">Application Web</h3> 
                            <p style="font-family: 'Scheherazade', serif; font-size: 26px">Vous avez besoin de gérer de manière efficace vos personnels, vos documents, vos magasins, vos institutions, ... </p> 
                            <a href="#application-web" class="btn btn-primary">Voir plus</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <!-- Set the second background image using inline CSS below. -->
                <div class="col-xs-12">
                    <div class="col-xs-6">
                        <img class="img-responsive center-block" src="<?php echo $this->basePath('img/slider/slide2.png'); ?>" alt="" />  
                    </div>
                    <div class="carousel-caption text-justify" >
                        <div class="col-lg-6"></div>
                        <div class="col-lg-6" style="background-color: black; opacity:  0.8;padding-bottom: 15px;">
                            <h3 style=";color: #EC971F;  font-family: 'Cormorant Upright', serif;">Web Services</h3> 
                            <p style="font-family: 'Scheherazade', serif; font-size: 26px">Obtenez des notifications en temps réel sur le bon fonctionnement de vos applications, par le biais d'une application mobile android.</p> 
                            <a href="#web-services" class="btn btn-primary">Voir plus</a><br>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Set the third background image using inline CSS below. -->
            <div class="item">
                <div class="col-xs-12">
                    <div class="col-xs-6">
                        <img class="img-responsive center-block" src="<?php echo $this->basePath('img/slider/slide3.png'); ?>" alt="" />  
                    </div>
                    <div class="carousel-caption text-justify" >
                        <div class="col-lg-6"></div>
                        <div class="col-lg-6" style="background-color: black; opacity:  0.8;padding-bottom: 15px;">
                            <h3 style=";color: #EC971F;  font-family: 'Cormorant Upright', serif;">Application Mobile</h3> 
                            <p style="font-family: 'Scheherazade', serif; font-size: 26px">Etendez vos entreprises, facilitez l'accès aux informations, retenez vos clients via l'application mobile.</p> 
                            <a href="#application-mobile" class="btn btn-primary">Voir plus</a><br>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="col-xs-12">
                    <div class="col-xs-6">
                        <img class="img-responsive center-block" src="<?php echo $this->basePath('img/slider/slide4.png'); ?>" alt="" />  
                    </div>
                    <div class="carousel-caption text-justify" >
                        <div class="col-lg-6"></div>
                        <div class="col-lg-6" style="background-color: black; opacity:  0.8; padding-bottom: 15px;">
                            <h3 style=";color: #EC971F;  font-family: 'Cormorant Upright', serif;">IT-Consulting</h3> 
                            <p style="font-family: 'Scheherazade', serif; font-size: 26px">Nous vous accompagnons par des conseils, des directives adéquats pour la réalisation informatisée de vos problèmes.</p> 
                            <a href="#it-consulting" class="btn btn-primary">Voir plus</a><br>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="col-xs-12">
                    <div class="col-xs-6">
                        <img class="img-responsive center-block" src="<?php echo $this->basePath('img/slider/slide5.png'); ?>" alt="" />  
                    </div>
                    <div class="carousel-caption text-justify" >
                        <div class="col-lg-6"></div>
                        <div class="col-lg-6" style="background-color: black; opacity:  0.8; padding-bottom: 15px;">
                            <h3 style=";color: #EC971F;  font-family: 'Cormorant Upright', serif;">Site Web</h3> 
                            <p style="font-family: 'Scheherazade', serif; font-size: 26px">Faites valoir vos activités, vos services et communiquez avec vos clients via un site web extrêment ergonomique et web responsive design.</p> 
                            <a href="#site-web" class="btn btn-primary">Voir plus</a><br>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>
    </div>
</div>
<script>
    $('.carousel').carousel({
        interval: 10000 //changes the speed
    })
</script>