<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <div class="col-lg-12">
            <p class="center-block text-center maintenance">Cette page est momentanément indisponible  ....</p>             
            <img class="img-responsive center-block" src="<?php echo $this->basePath('img/img1.gif'); ?>" width="500" height="700" />  
        </div>            
    </div>
</body>
</html>
