<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- css -->
        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/sassire.ico'])
                ->prependStylesheet($this->basePath('css/realisation/fancybox/jquery.fancybox.css'))
                ->prependStylesheet($this->basePath('css/realisation/jcarousel.css'))
                ->prependStylesheet($this->basePath('css/realisation/flexslider.css'))
                ->prependStylesheet($this->basePath('css/realisation/style.css'))
                ->prependStylesheet($this->basePath('css/realisation/default.css'))
        ?>



        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
              <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
            <![endif]-->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/realisation/jquery.easing.1.3.js'))
                ->prependFile($this->basePath('js/realisation/jquery.fancybox.pack.js'))
                ->prependFile($this->basePath('js/realisation/jquery.fancybox-media.js'))
                ->prependFile($this->basePath('js/realisation/google-code-prettify/prettify.js'))
                ->prependFile($this->basePath('js/realisation/portfolio/jquery.quicksand.js'))
                ->prependFile($this->basePath('js/realisation/portfolio/setting.js'))
                ->prependFile($this->basePath('js/realisation/jquery.flexslider.js'))
                ->prependFile($this->basePath('js/realisation/animate.js'))
                ->prependFile($this->basePath('js/realisation/custom.js'))
        ?>
    </head>
    <body>
        <div class="col-lg-12">
            <ul class="portfolio-categ filter">
                <li class="all active"><a href="#">TOUS</a></li>
                <li class="web"><a href="#" title="">Applications Mobiles</a></li>
                <li class="icon"><a href="#" title="">Applications web</a></li>
                <li class="graphic"><a href="#" title="">Sites Web</a></li>
                <li class="graphic"><a href="#" title="">Applications Bureau</a></li>
            </ul>
            <div class="clearfix">
            </div>
            <div class="row">
                <section id="projects">
                    <ul id="thumbs" class="portfolio">
                        <!-- Item Project and Filter Name -->
                        <li class="item-thumbs col-lg-3 design" data-id="id-0" data-type="web">
                            <!-- Fancybox - Gallery Enabled - Title - Full Image -->
                            <a class="hover-wrap fancybox" data-fancybox-group="gallery" title="Portfolio name" href="<?php echo $this->basePath('img/works/1.jpg'); ?>">
                                <span class="overlay-img"></span>
                                <span class="overlay-img-thumb font-icon-plus"></span>
                            </a>
                            <!-- Thumb Image and Description -->
                            <img src="<?php echo $this->basePath('img/works/1.jpg'); ?>" alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.">
                        </li>
                        <!-- End Item Project -->
                        <!-- Item Project and Filter Name -->
                        <li class="item-thumbs col-lg-3 design" data-id="id-1" data-type="icon">
                            <!-- Fancybox - Gallery Enabled - Title - Full Image -->
                            <a class="hover-wrap fancybox" data-fancybox-group="gallery" title="Portfolio name" href="<?php echo $this->basePath('img/works/2.jpg'); ?>">
                                <span class="overlay-img"></span>
                                <span class="overlay-img-thumb font-icon-plus"></span>
                            </a>
                            <!-- Thumb Image and Description -->
                            <img src="<?php echo $this->basePath('img/works/2.jpg'); ?>" alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.">
                        </li>
                        <!-- End Item Project -->
                        <!-- Item Project and Filter Name -->
                        <li class="item-thumbs col-lg-3 photography" data-id="id-2" data-type="graphic">
                            <!-- Fancybox - Gallery Enabled - Title - Full Image -->
                            <a class="hover-wrap fancybox" data-fancybox-group="gallery" title="Portfolio name" href="<?php echo $this->basePath('img/works/3.jpg'); ?>">
                                <span class="overlay-img"></span>
                                <span class="overlay-img-thumb font-icon-plus"></span>
                            </a>
                            <!-- Thumb Image and Description -->
                            <img src="<?php echo $this->basePath('img/works/3.jpg'); ?>" alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.">
                        </li>
                        <!-- End Item Project -->
                        <!-- Item Project and Filter Name -->
                        <li class="item-thumbs col-lg-3 design" data-id="id-0" data-type="web">
                            <!-- Fancybox - Gallery Enabled - Title - Full Image -->
                            <a class="hover-wrap fancybox" data-fancybox-group="gallery" title="Portfolio name" href="<?php echo $this->basePath('img/works/4.jpg'); ?>">
                                <span class="overlay-img"></span>
                                <span class="overlay-img-thumb font-icon-plus"></span>
                            </a>
                            <!-- Thumb Image and Description -->
                            <img src="<?php echo $this->basePath('img/works/4.jpg'); ?>" alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.">
                        </li>
                        <!-- End Item Project -->
                        <!-- Item Project and Filter Name -->
                        <li class="item-thumbs col-lg-3 photography" data-id="id-4" data-type="web">
                            <!-- Fancybox - Gallery Enabled - Title - Full Image -->
                            <a class="hover-wrap fancybox" data-fancybox-group="gallery" title="Portfolio name" href="<?php echo $this->basePath('img/works/5.jpg'); ?>">
                                <span class="overlay-img"></span>
                                <span class="overlay-img-thumb font-icon-plus"></span>
                            </a>
                            <!-- Thumb Image and Description -->
                            <img src="<?php echo $this->basePath('img/works/4.jpg'); ?>" alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.">
                        </li>
                        <!-- End Item Project -->
                        <!-- Item Project and Filter Name -->
                        <li class="item-thumbs col-lg-3 photography" data-id="id-5" data-type="icon">
                            <!-- Fancybox - Gallery Enabled - Title - Full Image -->
                            <a class="hover-wrap fancybox" data-fancybox-group="gallery" title="Portfolio name" href="<?php echo $this->basePath('img/works/5.jpg'); ?>">
                                <span class="overlay-img"></span>
                                <span class="overlay-img-thumb font-icon-plus"></span>
                            </a>
                            <!-- Thumb Image and Description -->
                            <img src="<?php echo $this->basePath('img/works/6.jpg'); ?>" alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.">
                        </li>
                        <!-- End Item Project -->
                        <li class="item-thumbs col-lg-3 design" data-id="id-0" data-type="web">
                            <!-- Fancybox - Gallery Enabled - Title - Full Image -->
                            <a class="hover-wrap fancybox" data-fancybox-group="gallery" title="Portfolio name" href="<?php echo $this->basePath('img/works/6.jpg'); ?>">
                                <span class="overlay-img"></span>
                                <span class="overlay-img-thumb font-icon-plus"></span>
                            </a>
                            <!-- Thumb Image and Description -->
                            <img src="<?php echo $this->basePath('img/works/7.jpg'); ?>" alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.">
                        </li>
                        <!-- End Item Project -->
                        <!-- Item Project and Filter Name -->
                        <li class="item-thumbs col-lg-3 design" data-id="id-0" data-type="graphic">
                            <!-- Fancybox - Gallery Enabled - Title - Full Image -->
                            <a class="hover-wrap fancybox" data-fancybox-group="gallery" title="Portfolio name" href="<?php echo $this->basePath('img/works/7.jpg'); ?>">
                                <span class="overlay-img"></span>
                                <span class="overlay-img-thumb font-icon-plus"></span>
                            </a>
                            <!-- Thumb Image and Description -->
                            <img src="<?php echo $this->basePath('img/works/8.jpg'); ?>" alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.">
                        </li>
                        <!-- End Item Project -->
                    </ul>
                </section>
            </div>
        </div>
        <a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>
        <!-- javascript
            ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->

    </body>
</html>
