<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.png'))
                ->prependStylesheet($this->basePath('customer/realisation/css/main.css'))
                ->prependStylesheet($this->basePath('customer/service/css/agency.css'));
        ?>


        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('customer/realisation/js/main.js'))
        ;
        ?>

    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="heading text-center col-sm-8 col-sm-offset-2 wow fadeInUp" data-wow-duration="1200ms" data-wow-delay="300ms">
                    <h2 class="element-item section-heading">NOS REALISATIONS</h2>
                </div>
            </div>
            <div class="blog-posts">
                <div class="row">
                    <div>
                        <div class="col-sm-9 wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="600ms">
                            <div class="center-block">
                                <h3><a href="#">GP-CICM (Application de gestion de personnels du Coeur Immaculée Marie)</a></h3>
                                <span class="date">Décembre 26, 2015</span>
                                <span class="cetagory">en  <strong>image</strong></span>
                            </div>
                            <div class="post-thumb">
                                <div id="post-carousel"  class="carousel slide" data-ride="carousel">
                                    <ol class="carousel-indicators">
                                        <li data-target="#post-carousel" data-slide-to="0" class="active"></li>
                                        <li data-target="#post-carousel" data-slide-to="1"></li>
                                        <li data-target="#post-carousel" data-slide-to="2"></li>
                                        <li data-target="#post-carousel" data-slide-to="3"></li>
                                        <li data-target="#post-carousel" data-slide-to="4"></li>
                                        <li data-target="#post-carousel" data-slide-to="5"></li>
                                    </ol>
                                    <div class="carousel-inner">
                                        <div class="item active">
                                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco1.jpg'); ?>" alt="" data-toggle="modal" data-target="#cicmaco1"></a>
                                        </div>
                                        <div class="item">
                                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco2.jpg'); ?>" alt="" data-toggle="modal" data-target="#cicmaco2"></a>
                                        </div>
                                        <div class="item">
                                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco3.jpg'); ?>" alt="" data-toggle="modal" data-target="#cicmaco3"></a>
                                        </div>
                                        <div class="item">
                                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco4.jpg'); ?>" data-toggle="modal" data-target="#cicmaco4" alt=""></a>
                                        </div>
                                        <div class="item">
                                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco5.jpg'); ?>" data-toggle="modal" data-target="#cicmaco5" alt=""></a>
                                        </div>
                                        <div class="item">
                                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco6.jpg'); ?>" data-toggle="modal" data-target="#cicmaco6" alt=""></a>
                                        </div>
                                    </div>                               
                                    <a class="blog-left-control" href="#post-carousel" role="button" data-slide="prev"><i class="fa fa-angle-left"></i></a>
                                    <a class="blog-right-control" href="#post-carousel" role="button" data-slide="next"><i class="fa fa-angle-right"></i></a>
                                </div>                            
                                <div class="post-meta">
                                    <span><i class="fa fa-comments-o"></i> 3 commentaires</span>
                                    <span><i class="fa fa-heart"></i> 0 Likes</span> 
                                </div>
                                <div class="post-icon">
                                    <i class="fa fa-picture-o"></i>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <h3>Fonctionnalités du CICMACO</h3>
                            <hr>
                            <ul>
                                <li>Gestion du personnel</li> <hr>
                                <li>Gestion des événements</li> <hr>
                                <li>Gestion des dossiers</li> <hr>
                                <li>Notifications par mail</li> <hr>
                                <li>Impression des CV</li> <hr>
                                <li>Impression de modèle de format</li> <hr>
                                <li>Gestion des historiques</li> <hr>
                            </ul>
                        </div>
                    </div> 
                </div>
            </div>

            <div class="blog-posts">
                <div class="row">
                    <div>
                        <div class="center-block">
                            <h3><a href="#">NATURGC GROUP (Site d'entreprise)</a></h3>
                            <span class="date">Octobre 26, 2015</span>
                            <span class="cetagory">en  <strong>image</strong></span>
                        </div>
                        <div class="col-sm-3">
                            <h3>Fonctionnalités du NATURGC</h3>
                            <hr>
                            <ul>
                                <li>Gestion du personnel</li> <hr>
                                <li>Gestion des événements</li> <hr>
                                <li>Gestion des dossiers</li> <hr>
                                <li>Notifications par mail</li> <hr>
                                <li>Impression des CV</li> <hr>
                                <li>Impression de modèle de format</li> <hr>
                                <li>Gestion des historiques</li> <hr>
                            </ul>
                        </div>
                        <div class="col-sm-9 wow fadeInUp" data-wow-duration="2000ms" data-wow-delay="1200ms">                            
                            <div class="post-thumb">
                                <div id="post-carousel"  class="carousel slide" data-ride="carousel">
                                    <ol class="carousel-indicators">
                                        <li data-target="#post-carousel" data-slide-to="0" class="active"></li>
                                        <li data-target="#post-carousel" data-slide-to="1"></li>
                                        <li data-target="#post-carousel" data-slide-to="2"></li>
                                    </ol>
                                    <div class="carousel-inner">
                                        <div class="item active">
                                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/naturgc/naturgc1.png'); ?>" alt="" data-toggle="modal" data-target="#cicmaco1"></a>
                                        </div>
                                        <div class="item">
                                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/naturgc/naturgc2.png'); ?>" alt="" data-toggle="modal" data-target="#cicmaco2"></a>
                                        </div>
                                        <div class="item">
                                            <a href="#"><img class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/naturgc/naturgc3.png'); ?>" alt="" data-toggle="modal" data-target="#cicmaco3"></a>
                                        </div>
                                    </div>                               
                                    <a class="blog-left-control" href="#post-carousel" role="button" data-slide="prev"><i class="fa fa-angle-left"></i></a>
                                    <a class="blog-right-control" href="#post-carousel" role="button" data-slide="next"><i class="fa fa-angle-right"></i></a>
                                </div>                            
                                <div class="post-meta">
                                    <span><i class="fa fa-comments-o"></i> 3 commentaires</span>
                                    <span><i class="fa fa-heart"></i> 0 Likes</span> 
                                </div>
                                <div class="post-icon">
                                    <i class="fa fa-picture-o"></i>
                                </div>
                            </div>
                        </div>
                    </div> 
                </div>
            </div>
            <!--partie correspondane aux modals-->
            <div class="modal" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                        </div>
                        <div class="modal-body">
                            <img width="100%" height="100%" class="img-responsive" src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco4.jpg'); ?>" alt="">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Save changes</button>
                        </div>
                    </div>
                </div>
            </div>


            <div class="modal fade" id="cicmaco1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"><br><br><br><br><br><br>
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <!--            <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>-->
                        <div class="modal-body">
                            <div id="myCarousel1" class="carousel slide">
                                <!-- Carousel indicators -->
                                <ol class="carousel-indicators">
                                    <li data-target="#myCarousel1" data-slide-to="0" class="active"></li>
                                    <li data-target="#myCarousel1" data-slide-to="1"></li>
                                    <li data-target="#myCarousel1" data-slide-to="2"></li>
                                    <li data-target="#myCarousel1" data-slide-to="3"></li>
                                    <li data-target="#myCarousel1" data-slide-to="4"></li>
                                    <li data-target="#myCarousel1" data-slide-to="5"></li>
                                    <li data-target="#myCarousel1" data-slide-to="6"></li>
                                </ol>
                                <!-- Carousel items -->
                                <div class="carousel-inner">
                                    <div class="item active">
                                        <img src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco2.jpg'); ?>" alt="First slide" class="img-responsive img-thumbnail" width="1000" height="800"> 
                                        <div class="carousel-caption" style="background-color: black;opacity: 0.5;color: #028FCC">Installation du panneau solaire à la Mairie de GUIDER</div>
                                    </div>
                                    <div class="item">
                                        <img src="img/obsic/realisations/2/Image67.jpg" alt="Second slide" class="img-responsive img-thumbnail" width="1000" height="800">
                                        <div class="carousel-caption">This Caption 2</div>
                                    </div>
                                    <div class="item">
                                        <img src="img/obsic/realisations/2/Image68.jpg" alt="First slide" class="img-responsive img-thumbnail" width="1000" height="800">
                                        <div class="carousel-caption">This Caption 3</div>
                                    </div>
                                    <div class="item">
                                        <img src="img/obsic/realisations/2/Image69.jpg" alt="First slide" class="img-responsive img-thumbnail" width="1000" height="800">
                                        <div class="carousel-caption">This Caption 3</div>
                                    </div>
                                    <div class="item">
                                        <img src="img/obsic/realisations/2/Image70.jpg" alt="First slide" class="img-responsive img-thumbnail" width="1000" height="800">
                                        <div class="carousel-caption">This Caption 3</div>
                                    </div>
                                    <div class="item">
                                        <img src="img/obsic/realisations/2/Image71.jpg" alt="First slide" class="img-responsive img-thumbnail" width="1000" height="800">
                                        <div class="carousel-caption">This Caption 3</div>
                                    </div>
                                    <div class="item">
                                        <img src="img/obsic/realisations/2/Image72.jpg" alt="First slide" class="img-responsive img-thumbnail" width="1000" height="800">
                                        <div class="carousel-caption">This Caption 3</div>
                                    </div>
                                </div>
                                <!-- Carousel nav --> 
                                <div>
                                    <a class="carousel-control left" href="#myCarousel1"
                                       data-slide="prev">&lsaquo;</a>
                                    <a class="carousel-control right" href="#myCarousel1"
                                       data-slide="next">&rsaquo;</a>
                                </div>
                            </div>
                        </div>
                        <script>
                            $('.carousel').carousel({
                                interval: 5000
                            });
                        </script>
                    </div>
                </div>
            </div>



            <div class="modal fade col-xs-12" id="cicmaco2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div style="margin-top: 25px">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <img class="img-responsive" width="25" height="25" src="<?php echo $this->basePath('customer/realisation/images/cross.png'); ?>" alt="">
                    </button>
                </div><div class="col-xs-10 col-xs-offset-1 realization-item">
                    <img src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco2.jpg'); ?>" class="img-responsive "alt="">
                </div>
            </div>


            <div class="modal fade col-xs-12" id="cicmaco3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div style="margin-top: 25px">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <img class="img-responsive" width="25" height="25" src="<?php echo $this->basePath('customer/realisation/images/cross.png'); ?>" alt="">
                    </button>
                </div>
                <div class="col-xs-10 col-xs-offset-1 realization-item">
                    <img src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco3.jpg'); ?>" alt="">
                </div>
            </div>
            <div class="modal fade col-xs-12" id="cicmaco4" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div style="margin-top: 25px">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <img class="img-responsive" width="25" height="25" src="<?php echo $this->basePath('customer/realisation/images/cross.png'); ?>" alt="">
                    </button>
                </div>
                <div class="col-xs-10 col-xs-offset-1 realization-item">
                    <img src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco4.jpg'); ?>" alt="">
                </div>
            </div>
            <div class="modal fade col-xs-12" id="cicmaco5" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div style="margin-top: 25px">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <img class="img-responsive" width="25" height="25" src="<?php echo $this->basePath('customer/realisation/images/cross.png'); ?>" alt="">
                    </button>
                </div>
                <div class="col-xs-10 col-xs-offset-1 realization-item">
                    <img src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco5.jpg'); ?>" alt="">
                </div>
            </div>
            <div class="modal fade col-xs-12" id="cicmaco6" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div style="margin-top: 25px">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <img class="img-responsive" width="25" height="25" src="<?php echo $this->basePath('customer/realisation/images/cross.png'); ?>" alt="">
                    </button>
                </div>
                <div class="col-xs-10 col-xs-offset-1 realization-item">
                    <img src="<?php echo $this->basePath('customer/realisation/images/cicmaco/cicmaco6.jpg'); ?>" alt="">
                </div>
            </div>
        </div>

    </body>

</html>


