<!DOCTYPE html>
<html lang="en">

    <head>

        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.png'))
                ->prependStylesheet($this->basePath('css/services/agency.css'))
        ?>




        <!-- Custom CSS -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('customer/service/js/classie.js'))
                ->prependFile($this->basePath('customer/service/js/cbpAnimatedHeader.js'))
                ->prependFile($this->basePath('customer/service/js/jqBootstrapValidation.js'))
                ->prependFile($this->basePath('customer/service/js/contact_me.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('customer/service/js/agency.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>

    <body id="page-top" class="index">
        <!-- Services Section -->

        <div class="container">
            <br> <br>
            <div class="row" id="services">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading element-item">Nos Services</h2>
                    <h3 class="section-subheading text-muted element-sub-item"><span style="color: #017DC3">SASSIRE,&nbsp;</span>Innovation Technologique en Afrique.</h3>
                </div>
            </div>
            <div class="row text-center">
                <div class="col-md-4">
                </div>
                <div class="col-md-4" id="application-web">
                    <h3 class="service-heading service-item" >Application Web</h3>
                    <a href="#portfolioModal9" class="portfolio-link" data-toggle="modal">
                        <img title="Cliquez dessus pour voir plus de détails" data-toggle="tooltip" width="300" height="450" src="<?php echo $this->basePath('img/services/cicmaco4.PNG'); ?>" class="center-block img-responsive img-circle" alt="">
                    </a> 
                    <h4 class="service-heading" >Développement des Applications Web</h4>
                    <p class="text-muted service-item-label">Vous êtes une Entreprise, une Société, une Organisation, un Etablissement, une Institution et vous avez besoin d'une application. N'hésitez pas à nous contacter <a href="http://sassire.com/public/application/Index/contact">www.sassire.com</a> .</p>
                </div>
                <div class="col-md-4">
                </div>
            </div>
            <div class="row text-center" >
                <div class="col-md-4" id="site-web">
                    <h3 class="service-heading service-item">Site-Web</h3>
                    <a href="#portfolioModal6" class="portfolio-link" data-toggle="modal">
                        <img title="Cliquez dessus pour voir plus de détails" data-toggle="tooltip" width="300" height="450" src="<?php echo $this->basePath('img/services/service_2.jpg'); ?>" title="Cliquez pour voir les détails" class="center-block img-responsive img-circle img-feature-1" alt="">
                    </a> 
                    <h4 class="service-heading">Conception des Sites Web</h4>
                    <p class="text-muted service-item-label">Vous avez besoin d'une Visibilité, d'une Notoriété, une Extension, etc. Vous auriez besoin d'un Site Web et c'est l'affaire de <a href="http://sassire.com/public/application/Index/contact">www.sassire.com</a></p>
                </div>
                <div class="col-md-4 center-block" id="web-services">
                    <h3 class="service-heading service-item">Web Services</h3>
                    <a href="#portfolioModal7" class="portfolio-link" data-toggle="modal">
                        <img title="Cliquez dessus pour voir plus de détails" data-toggle="tooltip" width="300" height="450" src="<?php echo $this->basePath('img/services/service_3.jpg'); ?>" class="center-block img-responsive img-circle img-feature-1" alt="">
                    </a> 
                    <h4 class="service-heading">Conception des Services Web Service</h4>
                    <p class="text-muted service-item-label">Vous avez besoin de superviser, de faire le suivi du fonctionnement d'un système, d'une plateforme via une tierce application mobile, veuillez nous contacter sur <a href="http://sassire.com/public/application/Index/contact">www.sassire.com</a></p>
                </div>
                <div class="col-md-4" id="it-consulting">
                    <h3 class="service-heading service-item">IT-Consulting</h3>
                    <a href="#portfolioModal10" class="portfolio-link" data-toggle="modal">
                        <img title="Cliquez dessus pour voir plus de détails" data-toggle="tooltip" width="300" height="450" src="<?php echo $this->basePath('img/services/service_4.jpg'); ?>" class="center-block img-responsive img-circle img-feature-1" alt="">
                    </a> 
                    <h4 class="service-heading">IT-Consulting</h4>
                    <p class="text-muted service-item-label">Vous avez besoin des conseils, des directives dans le processus d'informatisation et d'automatisation des vos problèmes, faites appel à <a href="http://sassire.com/public/application/Index/contact">www.sassire.com</a> .</p>
                </div>
            </div>
            <div class="row text-center" id="application-mobile">
                <div class="col-md-4">
                </div>
                <div class="col-md-4">
                    <h3 class="service-heading service-item">Application-Mobile</h3>
                    <a href="#portfolioModal8" class="portfolio-link" data-toggle="modal">
                        <img title="Cliquez dessus pour voir plus de détails" data-toggle="tooltip" width="300" height="450" src="<?php echo $this->basePath('img/services/service_5.png'); ?>" class="center-block img-responsive img-circle img-feature-1" alt="">
                    </a> 
                    <h4 class="service-heading">Développement des Applications Mobiles</h4>
                    <p class="text-muted service-item-label">Vous voulez étendre votre entreprise, faciliter l'accès aux informations, accroître la production et communiquer avec vos clients, l'application mobile serait une solution fiable et facile à mettre en place. Veuillez nous contacter à <a href="http://sassire.com/public/application/Index/contact">wwww.sassire.com</a>. </p>
                </div>
                <div class="col-md-4 center-block">
                </div>
            </div>            
        </div>

        <!-- Portfolio Grid Section -->
        <!-- About Section -->
        <div class="container">
            <br><br><br><br><br><br>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading element-item">A Propos de nous</h2>
                    <h3 class="section-subheading text-muted element-sub-item">La génèse de l'entreprise SASSIRE GROUP</h3>
                </div>
            </div>

            <br><br><br>
            <div class="row">
                <div class="col-lg-12">
                    <ul class="timeline">
                        <li>
                            <div class="timeline-image">
                                <img class="img-circle img-responsive" width="400" height="400" src="<?php echo $this->basePath('img/about/about_3.png'); ?>" alt="">
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4 class="team-item-title">2013-2014</h4>
                                    <h4 class="subheading">Commencement</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted p-service">Une équipe de 02 personnes<br>
                                        Développement des applications Web.<br>
                                        et<br>
                                        des sites Web</p>
                                </div>
                            </div>
                        </li>
                        <li class="timeline-inverted">
                            <div class="timeline-image">
                                <img class="img-circle img-responsive" src="<?php echo $this->basePath('img/about/about_4.png'); ?>" alt="">
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4 class="team-item-title">Mars 2014</h4>
                                    <h4 class="subheading">Innovation dans le monde des applications mobiles</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted p-service">Equipe de 03 personnes<br>
                                        Développement des applications Mobiles pour Android<br>
                                        Développement des services Web</p>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="timeline-image">
                                <img class="img-circle img-responsive" width="400" height="400" src="<?php echo $this->basePath('img/about/about_7.png'); ?>" alt="">
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4 class="team-item-title">Décembre 2014-2015</h4>
                                    <h4 class="subheading">Innovation Technologique</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted p-service">Utilisation des Technologies WEB 2.0 :<br>
                                        Bootstrap Twitter<br>
                                        JQuery<br>
                                        AJAX</p>
                                </div>
                            </div>
                        </li>
                        <li class="timeline-inverted">
                            <div class="timeline-image">
                                <img class="img-circle img-responsive" src="<?php echo $this->basePath('img/about/about_2.png'); ?>" alt="">
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4 class="team-item-title">2016</h4>
                                    <h4 class="subheading">Intégration du IT-Consulting</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted p-service">Conseils et directives dans l'informatisation et l'automatisation des Problèmes</p>
                                </div>
                            </div>
                        </li>
                        <li class="timeline-inverted">
                            <div class="timeline-image">
                                <img class="img-circle img-responsive" src="<?php echo $this->basePath('img/about/about_5.png'); ?>" alt="">
                            </div>

                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Team Section -->
        <div class="container" id="dreamteam">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading element-item">Notre Equipe</h2>
                    <h3 class="section-subheading text-muted element-sub-item">Une communauté d'Ingénieurs Chevronnés</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <div class="team-member">
                        <a href="#"  data-toggle="modal" data-target="#team1cv">
                            <img src="<?php echo $this->basePath('img/team/team1.jpg'); ?>" title="Voir détails" class="img-responsive img-circle" alt="" width="300" height="300">
                        </a>
                        <h4 class="team-item">PASSANG Gamaliel</h4>
                        <p class="text-muted team-paragraph">Ingénieur de Conception en Génie Logiciel</p>
                        <ul class="list-inline social-buttons">
                            <li><a href="#"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="team-member">
                        <a href="#"  data-toggle="modal" data-target="#team2cv">
                            <img src="<?php echo $this->basePath('img/team/team2.png'); ?>" title="Voir détails" class="img-responsive img-circle" alt="">
                        </a>
                        <h4 class="team-item">AMADOU BAKARI</h4>
                        <p class="text-muted team-paragraph">Architecte Système/Ingénieur de Conception des solutions Informatques </p>
                        <ul class="list-inline social-buttons">
                            <li><a href="#"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li><a href="https://www.facebook.com/amadoubakari.bakari"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="team-member">
                        <a href="#"  data-toggle="modal" data-target="#team3cv">
                            <img src="<?php echo $this->basePath('img/team/team3.jpg'); ?>" title="Voir détails" class="img-responsive img-circle" alt="" width="300" height="300">
                        </a>
                        <h4 class="team-item">BIVAGAI OMAR</h4>
                        <p class="text-muted team-paragraph">Analyste Programmeur</p>
                        <ul class="list-inline social-buttons">
                            <li><a href="#"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <p class="large text-muted"></p>
                </div>
            </div>
        </div>




        <div class="portfolio-modal modal fade" id="portfolioModal6" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="modal-body">
                                <!-- Project Details Go Here -->
                                <h2>Sites Web</h2>
                                <p class="item-intro text-muted service-item-label">Conception des Sites Web</p>
                                <img class="img-responsive img-centered" src="<?php echo $this->basePath('img/services/service_2.jpg'); ?>" alt="">
                                <p class="service-item-label">Soyez Visible sur la Toile Mondiale, Augmenter votre popularité et maximiser votre clientèle via un site:</p>
                                <h3>Nous concevons toute catégorie de site</h3>
                                <ul class="list-unstyled">
                                    <li>
                                        <h4 class="service-heading">sites e-commerce</h4>
                                        <p class="service-item-label">Les sites marchands permettent de vendre directement vos produits aux internautes qui procèdent au paiement directement en ligne.</p>
                                    </li>
                                    <li> 
                                        <h4 class="service-heading"> Sites Vitrines</h4>
                                        <p class="service-item-label">Rôle d’information mettant en avant l’image de marque de votre entreprise, en présentant votre activité, vos produits, vos services.</p>
                                    </li>
                                    <li>
                                        <h4 class="service-heading">Sites Institutionnels</h4>
                                        <p class="service-item-label">Présentation de l’organisation et des valeurs de l’entreprise, par la description de l’activité, la transmission de chiffres clés et des ‘informations nécessaires au public ciblé.</p>
                                    </li>
                                    <li>
                                        <h4 class="service-heading">Sites Personnels</h4>
                                        <p class="service-item-label"> Sites réalisés par des particuliers, le plus souvent par passion pour un sujet précis.</p>
                                    </li>                                    
                                    <li>
                                        <h4 class="service-heading"> Site communautaires</h4>
                                        <p class="service-item-label">Les réseaux sociaux permettent aux internautes de se réunir autour d’un intérêt commun, d’un partage d’informations.</p>
                                    </li>
                                    <li>
                                        <h4 class="service-heading"> Sites Blog</h4>
                                        <p class="service-item-label">Plus ouverts que les sites personnels; les visiteurs peuvent laisser leurs commentaires.</p>
                                    </li>
                                </ul>
                                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Fermer</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="portfolio-modal modal fade" id="portfolioModal7" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="modal-body">
                                <!-- Project Details Go Here -->
                                <h2>Web Services </h2>
                                <p class="item-intro text-muted">Conception des WEB Services</p>
                                <img class="img-responsive img-centered" src="<?php echo $this->basePath('img/services/service_3.jpg'); ?>" alt="">
                                <p class="service-item-label">Vous avez besoin de superviser, de faire le suivi du fonctionnement d'un système, d'une plateforme via une tierce application mobile, veuillez nous contacter</p>
                                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close Project</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="portfolio-modal modal fade" id="portfolioModal8" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="modal-body">
                                <!-- Project Details Go Here -->
                                <h2>Application mobile</h2>
                                <p class="item-intro text-muted service-item-label">Conception des Applications Mobiles</p>
                                <img class="img-responsive img-centered" src="<?php echo $this->basePath('img/services/service_5.png'); ?>" alt="">
                                <p  class="service-item-label">Etendez vos entreprises, augmentez la production des vos employés, facilitez l'accès aux informations grâce aux applications mobiles.</p>
                                <h3 class="service-heading">Catégories des Applications Mobiles que nous développns</h3>
                                <ul class="unstyled">
                                    <li>Applications de Géolocalisation</li>
                                    <li>Application mobile de e-commerce</li>
                                    <li>Application Mobile pour Web Service</li>
                                </ul>
                                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Fermer</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="portfolio-modal modal fade" id="portfolioModal9" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="modal-body">
                                <!-- Project Details Go Here -->
                                <h2>Application Web</h2>
                                <p class="item-intro text-muted">Développement des Applications Web ....</p>
                                <img class="img-responsive img-centered" src="<?php echo $this->basePath('img/services/cicmaco5.PNG'); ?>" alt="">
                                <p class="service-item-label">Votre application accessible et disponible 24h/24 et 7jr/7. La sécurité et la confifentialité de vos données. N'ignorez pas l'aspect Adaptabilité de l'application sur n'importe quel terminal (Tablette, SmartPhone, Ordinateur). chez &nbsp;<a href="https://www.behance.net/MathavanJaya">Sassire group</a> </p>
                                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Fermer</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="portfolio-modal modal fade" id="portfolioModal10" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="modal-body">
                                <!-- Project Details Go Here -->
                                <h2>Site Web</h2>
                                <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
                                <img class="img-responsive img-centered" src="<?php echo $this->basePath('img/services/service_4.jpg'); ?>" alt="">
                                <p>Dreams is a free PSD web template built by <a href="https://www.behance.net/MathavanJaya">Mathavan Jaya</a>. Dreams is a modern one page web template designed for almost any purpose. It’s a beautiful template that’s designed with the Bootstrap framework in mind.</p>
                                <p>You can download the PSD template in this portfolio sample item at <a href="http://freebiesxpress.com/gallery/dreams-free-one-page-web-template/">FreebiesXpress.com</a>.</p>
                                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close Project</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="portfolio-modal modal fade" id="portfolioModal11" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="modal-body">
                                <!-- Project Details Go Here -->
                                <h2>Site Web</h2>
                                <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
                                <img class="img-responsive img-centered" src="<?php echo $this->basePath('customer/service/img/native.png'); ?>" alt="">
                                <p>Dreams is a free PSD web template built by <a href="https://www.behance.net/MathavanJaya">Mathavan Jaya</a>. Dreams is a modern one page web template designed for almost any purpose. It’s a beautiful template that’s designed with the Bootstrap framework in mind.</p>
                                <p>You can download the PSD template in this portfolio sample item at <a href="http://freebiesxpress.com/gallery/dreams-free-one-page-web-template/">FreebiesXpress.com</a>.</p>
                                <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close Project</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--cv amadou bakari-->
        <div class="modal fade col-lg-12" id="team2cv" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="padding-top: 5%">
            <div class="col-lg-3"></div>
            <div class="col-lg-6 aligncenter" style="border: 2px solid #CBE6F4;background-color: white;padding-top: 2%">
                <div class="col-xs-12">
                    <div class="col-xs-4">
                        <img class="img-responsive img-circle" src="<?php echo $this->basePath('img/team/team2.png'); ?>" alt="">
                    </div>
                    <div class="col-xs-8">
                        <ul class="list-unstyled">
                            <li style="color: black; opacity: 06; font-weight: bold; margin-top: 10px;margin-bottom: 10px"><span class="cv-value"> &nbsp; AMADOU BAKARI</span></li>
                            <li style="color: black; opacity: 06; font-weight: bold; margin-top: 10px;margin-bottom: 10px"><span class="cv-value">Ingénieur de conception en génie logiciel de l'Ecole Nationale Supérieure Polytechnique du Sahel</span></li>
                            <li style="color: black; opacity: 06; font-weight: bold; margin-top: 10px;margin-bottom: 10px"><span class="cv-value">&nbsp;03 ans d'expérience </span></li>
                            <li style="color: black; opacity: 06; font-weight: bold; margin-top: 10px;margin-bottom: 10px"><span class="cv-value">&nbsp;Compétences en J2EE, PHP 5.X, Android, MySQL</span></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <!--cv gamaliel passang-->
        <div class="modal fade col-lg-12" id="team1cv" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="padding-top: 5%">
            <div class="col-lg-3"></div>
            <div class="col-lg-6 aligncenter" style="border: 2px solid #CBE6F4;background-color: white;padding-top: 2%">
                <div class="col-xs-12">
                    <div class="col-xs-4">
                        <img class="img-responsive img-circle" src="<?php echo $this->basePath('img/team/team1.jpg'); ?>" alt="">
                    </div>
                    <div class="col-xs-8">
                        <ul class="list-unstyled">
                            <li style="color: black; opacity: 06; font-weight: bold; margin-top: 10px;margin-bottom: 10px"><span class="cv-value"> &nbsp; PASSANG Gamaliel</span></li>
                            <li style="color: black; opacity: 06; font-weight: bold; margin-top: 10px;margin-bottom: 10px"><span class="cv-value">&nbsp;Ingénieur de Conception en Génie Logiciel de l'Ecole Nationale Supérieure Polytechnique du Sahel</span></li>
                            <li style="color: black; opacity: 06; font-weight: bold; margin-top: 10px;margin-bottom: 10px"><span class="cv-value">&nbsp;03 ans d'expériences</span></li>
                            <li style="color: black; opacity: 06; font-weight: bold; margin-top: 10px;margin-bottom: 10px"><span class="cv-value">&nbsp;Compétences Angular JS, PHP 5.X, MySQl, J2EE, Zend 3 Framework</span></li>
                        </ul>
                    </div>
                </div>              
            </div>
        </div>

        <!--cv omar bivagai-->
        <div class="modal fade col-lg-12" id="team3cv" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="padding-top: 5%">
            <div class="col-lg-3"></div>
            <div class="col-lg-6 aligncenter" style="border: 2px solid #CBE6F4;background-color: white;padding-top: 2%">
                <div class="col-xs-12">
                    <div class="col-xs-4">
                        <img class="img-responsive img-circle" src="<?php echo $this->basePath('img/team/team3.jpg'); ?>" alt="">
                    </div>
                    <div class="col-xs-8">
                        <ul class="list-unstyled">
                            <li style="color: black; opacity: 06; font-weight: bold; margin-top: 10px;margin-bottom: 10px"><span class="cv-value"> &nbsp; BIVAGAI OMAR</span></li>
                            <li style="color: black; opacity: 06; font-weight: bold; margin-top: 10px;margin-bottom: 10px"><span class="cv-value">&nbsp;Ingéneur des Travaux en Informatiqe de Gestion</span></li>
                            <li style="color: black; opacity: 06; font-weight: bold; margin-top: 10px;margin-bottom: 10px"><span class="cv-value">&nbsp;05 ans d'expériences</span></li>
                            <li style="color: black; opacity: 06; font-weight: bold; margin-top: 10px;margin-bottom: 10px"><span class="cv-value">&nbsp;PHP 5.X, MySQL, Symfony, Bootstrap, J2EE</span></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3"></div>
    </div>

    <!-- Scripts -->

    <script>


    </script>
</body>

</html>
